<?php
/**
 * Employee Financial Analysis - Organizational Level
 * Comprehensive analysis of employee costs vs organizational value and performance
 */

// Get comprehensive employee and organizational data
$employees = Employee::employees([], false, $DBConn);
$projects = Projects::projects_full([], false, $DBConn);

// Initialize organizational employee metrics
$orgEmployeeMetrics = [
    'overall_metrics' => [
        'total_employees' => 0,
        'total_annual_cost' => 0,
        'total_monthly_cost' => 0,
        'avg_cost_per_employee' => 0,
        'total_revenue_generated' => 0,
        'revenue_per_employee' => 0,
        'cost_benefit_ratio' => 0,
        'organizational_roi' => 0,
        'total_time_logged' => 0,
    ],
    'department_analysis' => [],
    'role_analysis' => [],
    'performance_tiers' => [
        'high_performers' => [],
        'average_performers' => [],
        'low_performers' => []
    ],
    'organizational_insights' => []
];

// Process employee data for organizational analysis
if ($employees) {
    foreach ($employees as $employee) {
      $unitAssignments = Employee::user_unit_assignments(['userID'=>$employee->ID, 'Suspended'=>'N'], false, $DBConn);
      // var_dump($unitAssignments);
      $department=$unitAssignments[0]->unitName ?? 'Unknown';

      // var_dump($employee);
      $numberOfHoursInCurrentMonth = 0;
      $numberOfHoursInCurrentMonth = Workutils::get_total_hours_in_month(date('m'), date('Y'), $DBConn);
      // var_dump($numberOfHoursInCurrentMonth);
        $orgEmployeeMetrics['overall_metrics']['total_employees']++;
        
        // Calculate employee costs
        $costPerHour = $employee->basicSalary/$numberOfHoursInCurrentMonth ?? 0;
        $dailyHours = $employee->dailyHours ?? 8;
        $weekWorkDays = $employee->weekWorkDays ?? 5;
        $monthlyHours = $dailyHours * $weekWorkDays * 4.33;
        $annualHours = $dailyHours * $weekWorkDays * 52;
        $monthlyCost = $employee->basicSalary;
        $annualCost = $employee->basicSalary * 12;
        
        $orgEmployeeMetrics['overall_metrics']['total_annual_cost'] += $annualCost;
        $orgEmployeeMetrics['overall_metrics']['total_monthly_cost'] += $monthlyCost;
        
        // Calculate revenue generated by this employee
        $employeeProjects = array_filter($projects, function($project) use ($employee) {
            return $project->projectOwnerID == $employee->ID || 
                   (isset($project->projectManagersIDs) && strpos($project->projectManagersIDs, $employee->ID) !== false);
        });

        //employee revenue generated based on the number of hours worked in the current month
        $employeeTimeLogs = TimeAttendance::project_tasks_time_logs_full(['employeeID'=>$employee->ID, 'Suspended'=>'N'], false, $DBConn);
        $employeeRevenue = 0;
        $totalTimeLogged = 0;
        if($employeeTimeLogs) {
         // var_dump($employeeTimeLogs);
            foreach ($employeeTimeLogs as $timeLog) {
                $decimalTime = (isSet($timeLog->taskDuration) && !empty($timeLog->taskDuration)) ?Utility::Time_to_decimal($timeLog->taskDuration): 0;
                $totalTimeLogged += $decimalTime ?? 0;
                $employeeRevenue += $timeLog->billableRateValue*$decimalTime ?? 0;
               
            }
        }
        
      //   $employeeRevenue = 0;
      //   foreach ($employeeProjects as $project) {
      //       $employeeRevenue += $project->billableRateValue ?? 0;
      //   }
        $orgEmployeeMetrics['overall_metrics']['total_time_logged'] += $totalTimeLogged;
        $orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] += $employeeRevenue;
        
        // Department analysis
      //   $department = $employee->businessUnitName ?? 'Unknown';
        if (!isset($orgEmployeeMetrics['department_analysis'][$department])) {
            $orgEmployeeMetrics['department_analysis'][$department] = [
                'employee_count' => 0,
                'total_cost' => 0,
                'total_revenue' => 0,
                'avg_cost_per_employee' => 0,
                'revenue_per_employee' => 0,
                'cost_benefit_ratio' => 0,
                'efficiency_score' => 0
            ];
        }
        
        $orgEmployeeMetrics['department_analysis'][$department]['employee_count']++;
        $orgEmployeeMetrics['department_analysis'][$department]['total_cost'] += $annualCost;
        $orgEmployeeMetrics['department_analysis'][$department]['total_revenue'] += $employeeRevenue;
        
        // Role analysis
        $role = $employee->jobTitle ?? 'Unknown';
        if (!isset($orgEmployeeMetrics['role_analysis'][$role])) {
            $orgEmployeeMetrics['role_analysis'][$role] = [
                'employee_count' => 0,
                'total_cost' => 0,
                'total_revenue' => 0,
                'avg_cost_per_employee' => 0,
                'revenue_per_employee' => 0,
                'cost_benefit_ratio' => 0,
                'efficiency_score' => 0
            ];
        }
        
        $orgEmployeeMetrics['role_analysis'][$role]['employee_count']++;
        $orgEmployeeMetrics['role_analysis'][$role]['total_cost'] += $annualCost;
        $orgEmployeeMetrics['role_analysis'][$role]['total_revenue'] += $employeeRevenue;
        
        // Calculate individual performance metrics
        $roi = $annualCost > 0 ? (($employeeRevenue - $annualCost) / $annualCost) * 100 : 0;
        $costBenefitRatio = $annualCost > 0 ? $employeeRevenue / $annualCost : 0;
        
        // Categorize performance
        if ($roi >= 100) {
            $orgEmployeeMetrics['performance_tiers']['high_performers'][] = [
                'employee' => $employee,
                'roi' => $roi,
                'cost_benefit_ratio' => $costBenefitRatio,
                'revenue' => $employeeRevenue,
                'cost' => $annualCost
            ];
        } elseif ($roi >= 0) {
            $orgEmployeeMetrics['performance_tiers']['average_performers'][] = [
                'employee' => $employee,
                'roi' => $roi,
                'cost_benefit_ratio' => $costBenefitRatio,
                'revenue' => $employeeRevenue,
                'cost' => $annualCost
            ];
        } else {
            $orgEmployeeMetrics['performance_tiers']['low_performers'][] = [
                'employee' => $employee,
                'roi' => $roi,
                'cost_benefit_ratio' => $costBenefitRatio,
                'revenue' => $employeeRevenue,
                'cost' => $annualCost
            ];
        }
    }
}

// Calculate derived organizational metrics
$orgEmployeeMetrics['overall_metrics']['avg_cost_per_employee'] = $orgEmployeeMetrics['overall_metrics']['total_employees'] > 0 ? 
    $orgEmployeeMetrics['overall_metrics']['total_annual_cost'] / $orgEmployeeMetrics['overall_metrics']['total_employees'] : 0;

$orgEmployeeMetrics['overall_metrics']['revenue_per_employee'] = $orgEmployeeMetrics['overall_metrics']['total_employees'] > 0 ? 
    $orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] / $orgEmployeeMetrics['overall_metrics']['total_employees'] : 0;

$orgEmployeeMetrics['overall_metrics']['cost_benefit_ratio'] = $orgEmployeeMetrics['overall_metrics']['total_annual_cost'] > 0 ? 
    $orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] / $orgEmployeeMetrics['overall_metrics']['total_annual_cost'] : 0;

$orgEmployeeMetrics['overall_metrics']['organizational_roi'] = $orgEmployeeMetrics['overall_metrics']['total_annual_cost'] > 0 ? 
    (($orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] - $orgEmployeeMetrics['overall_metrics']['total_annual_cost']) / $orgEmployeeMetrics['overall_metrics']['total_annual_cost']) * 100 : 0;

// Calculate department metrics
foreach ($orgEmployeeMetrics['department_analysis'] as $dept => &$data) {
    $data['avg_cost_per_employee'] = $data['employee_count'] > 0 ? $data['total_cost'] / $data['employee_count'] : 0;
    $data['revenue_per_employee'] = $data['employee_count'] > 0 ? $data['total_revenue'] / $data['employee_count'] : 0;
    $data['cost_benefit_ratio'] = $data['total_cost'] > 0 ? $data['total_revenue'] / $data['total_cost'] : 0;
    $data['efficiency_score'] = $data['cost_benefit_ratio'] * 100; // Convert to percentage
}

// Calculate role metrics
foreach ($orgEmployeeMetrics['role_analysis'] as $role => &$data) {
    $data['avg_cost_per_employee'] = $data['employee_count'] > 0 ? $data['total_cost'] / $data['employee_count'] : 0;
    $data['revenue_per_employee'] = $data['employee_count'] > 0 ? $data['total_revenue'] / $data['employee_count'] : 0;
    $data['cost_benefit_ratio'] = $data['total_cost'] > 0 ? $data['total_revenue'] / $data['total_cost'] : 0;
    $data['efficiency_score'] = $data['cost_benefit_ratio'] * 100; // Convert to percentage
}

// Sort departments and roles by efficiency
uasort($orgEmployeeMetrics['department_analysis'], function($a, $b) {
    return $b['efficiency_score'] <=> $a['efficiency_score'];
});

uasort($orgEmployeeMetrics['role_analysis'], function($a, $b) {
    return $b['efficiency_score'] <=> $a['efficiency_score'];
});

// Generate organizational insights
$orgEmployeeMetrics['organizational_insights'] = [
    'total_investment' => $orgEmployeeMetrics['overall_metrics']['total_annual_cost'],
    'total_return' => $orgEmployeeMetrics['overall_metrics']['total_revenue_generated'],
    'net_profit' => $orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] - $orgEmployeeMetrics['overall_metrics']['total_annual_cost'],
    'profit_margin' => $orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] > 0 ? 
        (($orgEmployeeMetrics['overall_metrics']['total_revenue_generated'] - $orgEmployeeMetrics['overall_metrics']['total_annual_cost']) / $orgEmployeeMetrics['overall_metrics']['total_revenue_generated']) * 100 : 0,
    'most_efficient_department' => array_key_first($orgEmployeeMetrics['department_analysis']),
    'most_efficient_role' => array_key_first($orgEmployeeMetrics['role_analysis']),
    'high_performer_percentage' => $orgEmployeeMetrics['overall_metrics']['total_employees'] > 0 ? 
        (count($orgEmployeeMetrics['performance_tiers']['high_performers']) / $orgEmployeeMetrics['overall_metrics']['total_employees']) * 100 : 0
];

?>

<div class="container-fluid">
    <!-- Organizational Employee Financial Overview -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-building-line me-2"></i>Organizational Employee Financial Analysis
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-3 col-md-6 mb-3">
                            <div class="card bg-white shadow-sm">
                                <div class="card-body text-center">
                                    <div class="avatar-sm bg-primary-subtle rounded mx-auto mb-3">
                                        <span class="avatar-title bg-primary-subtle text-primary rounded">
                                            <i class="ri-team-line fs-20"></i>
                                        </span>
                                    </div>
                                    <h4 class="mb-1 text-primary"><?= $orgEmployeeMetrics['overall_metrics']['total_employees'] ?></h4>
                                    <p class="text-muted mb-0">Total Employees</p>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xl-3 col-md-6 mb-3">
                            <div class="card bg-white shadow-sm">
                                <div class="card-body text-center">
                                    <div class="avatar-sm bg-danger-subtle rounded mx-auto mb-3">
                                        <span class="avatar-title bg-danger-subtle text-danger rounded">
                                            <i class="ri-money-dollar-circle-line fs-20"></i>
                                        </span>
                                    </div>
                                    <h4 class="mb-1 text-danger">KES <?= number_format($orgEmployeeMetrics['overall_metrics']['total_annual_cost'], 0) ?></h4>
                                    <p class="text-muted mb-0">Total Annual Cost</p>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xl-3 col-md-6 mb-3">
                            <div class="card bg-white shadow-sm">
                                <div class="card-body text-center">
                                    <div class="avatar-sm bg-success-subtle rounded mx-auto mb-3">
                                        <span class="avatar-title bg-success-subtle text-success rounded">
                                            <i class="ri-trending-up-line fs-20"></i>
                                        </span>
                                    </div>
                                    <h4 class="mb-1 text-success">KES <?= number_format($orgEmployeeMetrics['overall_metrics']['total_revenue_generated'], 0) ?></h4>
                                    <p class="text-muted mb-0">Total Revenue Generated</p>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-xl-3 col-md-6 mb-3">
                            <div class="card bg-white shadow-sm">
                                <div class="card-body text-center">
                                    <div class="avatar-sm bg-info-subtle rounded mx-auto mb-3">
                                        <span class="avatar-title bg-info-subtle text-info rounded">
                                            <i class="ri-percent-line fs-20"></i>
                                        </span>
                                    </div>
                                    <h4 class="mb-1 text-info"><?= number_format($orgEmployeeMetrics['overall_metrics']['organizational_roi'], 1) ?>%</h4>
                                    <p class="text-muted mb-0">Organizational ROI</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Key Organizational Metrics -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-calculator-line me-2"></i>Key Organizational Metrics
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-2 col-md-4 col-sm-6 mb-3">
                            <div class="text-center">
                                <h5 class="text-primary">KES <?= number_format($orgEmployeeMetrics['overall_metrics']['avg_cost_per_employee'], 0) ?></h5>
                                <small class="text-muted">Avg Cost per Employee</small>
                            </div>
                        </div>
                        <div class="col-xl-2 col-md-4 col-sm-6 mb-3">
                            <div class="text-center">
                                <h5 class="text-success">KES <?= number_format($orgEmployeeMetrics['overall_metrics']['revenue_per_employee'], 0) ?></h5>
                                <small class="text-muted">Revenue per Employee</small>
                            </div>
                        </div>
                        <div class="col-xl-2 col-md-4 col-sm-6 mb-3">
                            <div class="text-center">
                                <h5 class="text-info"><?= number_format($orgEmployeeMetrics['overall_metrics']['cost_benefit_ratio'], 2) ?></h5>
                                <small class="text-muted">Cost-Benefit Ratio</small>
                            </div>
                        </div>
                        <div class="col-xl-2 col-md-4 col-sm-6 mb-3">
                            <div class="text-center">
                                <h5 class="text-warning">KES <?= number_format($orgEmployeeMetrics['organizational_insights']['net_profit'], 0) ?></h5>
                                <small class="text-muted">Net Profit</small>
                            </div>
                        </div>
                        <div class="col-xl-2 col-md-4 col-sm-6 mb-3">
                            <div class="text-center">
                                <h5 class="text-danger"><?= number_format($orgEmployeeMetrics['organizational_insights']['profit_margin'], 1) ?>%</h5>
                                <small class="text-muted">Profit Margin</small>
                            </div>
                        </div>
                        <div class="col-xl-2 col-md-4 col-sm-6 mb-3">
                            <div class="text-center">
                                <h5 class="text-dark"><?= number_format($orgEmployeeMetrics['organizational_insights']['high_performer_percentage'], 1) ?>%</h5>
                                <small class="text-muted">High Performers</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Department Performance Analysis -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-building-line me-2"></i>Department Performance Analysis
                    </h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Department</th>
                                    <th>Employees</th>
                                    <th>Total Cost</th>
                                    <th>Total Revenue</th>
                                    <th>Avg Cost/Employee</th>
                                    <th>Revenue/Employee</th>
                                    <th>Cost-Benefit Ratio</th>
                                    <th>Efficiency Score</th>
                                    <th>Performance</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($orgEmployeeMetrics['department_analysis'] as $dept => $data): ?>
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <div class="avatar-sm bg-light rounded me-2">
                                                <span class="avatar-title bg-light text-dark rounded">
                                                    <i class="ri-building-line"></i>
                                                </span>
                                            </div>
                                            <div>
                                                <h6 class="mb-0"><?= htmlspecialchars($dept) ?></h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="badge bg-primary-subtle text-primary"><?= $data['employee_count'] ?></span>
                                    </td>
                                    <td>KES <?= number_format($data['total_cost'], 0) ?></td>
                                    <td>KES <?= number_format($data['total_revenue'], 0) ?></td>
                                    <td>KES <?= number_format($data['avg_cost_per_employee'], 0) ?></td>
                                    <td>KES <?= number_format($data['revenue_per_employee'], 0) ?></td>
                                    <td>
                                        <span class="<?= $data['cost_benefit_ratio'] >= 2 ? 'text-success' : ($data['cost_benefit_ratio'] >= 1 ? 'text-warning' : 'text-danger') ?>">
                                            <?= number_format($data['cost_benefit_ratio'], 2) ?>
                                        </span>
                                    </td>
                                    <td>
                                        <?php 
                                        $efficiencyClass = $data['efficiency_score'] >= 200 ? 'bg-success-subtle text-success' : 
                                                         ($data['efficiency_score'] >= 100 ? 'bg-warning-subtle text-warning' : 'bg-danger-subtle text-danger');
                                        ?>
                                        <span class="badge <?= $efficiencyClass ?>"><?= number_format($data['efficiency_score'], 0) ?></span>
                                    </td>
                                    <td>
                                        <?php 
                                        $performance = $data['efficiency_score'] >= 200 ? 'Excellent' : 
                                                     ($data['efficiency_score'] >= 100 ? 'Good' : 'Needs Improvement');
                                        $performanceClass = $data['efficiency_score'] >= 200 ? 'bg-success-subtle text-success' : 
                                                          ($data['efficiency_score'] >= 100 ? 'bg-warning-subtle text-warning' : 'bg-danger-subtle text-danger');
                                        ?>
                                        <span class="badge <?= $performanceClass ?>"><?= $performance ?></span>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Performance Tier Analysis -->
    <div class="row mb-4">
        <div class="col-xl-4 col-md-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-trophy-line me-2"></i>High Performers
                    </h5>
                </div>
                <div class="card-body">
                    <div class="text-center mb-3">
                        <div class="avatar-sm bg-success-subtle rounded mx-auto mb-3">
                            <span class="avatar-title bg-success-subtle text-success rounded">
                                <i class="ri-trophy-line fs-20"></i>
                            </span>
                        </div>
                        <h4 class="text-success"><?= count($orgEmployeeMetrics['performance_tiers']['high_performers']) ?></h4>
                        <p class="text-muted mb-0">Employees with ROI ≥ 100%</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <th>Employee</th>
                                    <th>ROI</th>
                                    <th>Revenue</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach (array_slice($orgEmployeeMetrics['performance_tiers']['high_performers'], 0, 5) as $performer): ?>
                                <tr>
                                    <td>
                                        <small><?= htmlspecialchars($performer['employee']->employeeName) ?></small>
                                    </td>
                                    <td>
                                        <span class="badge bg-success-subtle text-success"><?= number_format($performer['roi'], 0) ?>%</span>
                                    </td>
                                    <td>
                                        <small>KES <?= number_format($performer['revenue'], 0) ?></small>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-user-line me-2"></i>Average Performers
                    </h5>
                </div>
                <div class="card-body">
                    <div class="text-center mb-3">
                        <div class="avatar-sm bg-warning-subtle rounded mx-auto mb-3">
                            <span class="avatar-title bg-warning-subtle text-warning rounded">
                                <i class="ri-user-line fs-20"></i>
                            </span>
                        </div>
                        <h4 class="text-warning"><?= count($orgEmployeeMetrics['performance_tiers']['average_performers']) ?></h4>
                        <p class="text-muted mb-0">Employees with ROI 0-99%</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <th>Employee</th>
                                    <th>ROI</th>
                                    <th>Revenue</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach (array_slice($orgEmployeeMetrics['performance_tiers']['average_performers'], 0, 5) as $performer): ?>
                                <tr>
                                    <td>
                                        <small><?= htmlspecialchars($performer['employee']->employeeName) ?></small>
                                    </td>
                                    <td>
                                        <span class="badge bg-warning-subtle text-warning"><?= number_format($performer['roi'], 0) ?>%</span>
                                    </td>
                                    <td>
                                        <small>KES <?= number_format($performer['revenue'], 0) ?></small>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-alert-line me-2"></i>Low Performers
                    </h5>
                </div>
                <div class="card-body">
                    <div class="text-center mb-3">
                        <div class="avatar-sm bg-danger-subtle rounded mx-auto mb-3">
                            <span class="avatar-title bg-danger-subtle text-danger rounded">
                                <i class="ri-alert-line fs-20"></i>
                            </span>
                        </div>
                        <h4 class="text-danger"><?= count($orgEmployeeMetrics['performance_tiers']['low_performers']) ?></h4>
                        <p class="text-muted mb-0">Employees with ROI < 0%</p>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <th>Employee</th>
                                    <th>ROI</th>
                                    <th>Revenue</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach (array_slice($orgEmployeeMetrics['performance_tiers']['low_performers'], 0, 5) as $performer): ?>
                                <tr>
                                    <td>
                                        <small><?= htmlspecialchars($performer['employee']->employeeName) ?></small>
                                    </td>
                                    <td>
                                        <span class="badge bg-danger-subtle text-danger"><?= number_format($performer['roi'], 0) ?>%</span>
                                    </td>
                                    <td>
                                        <small>KES <?= number_format($performer['revenue'], 0) ?></small>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Charts -->
    <div class="row mb-4">
        <div class="col-xl-6 col-md-12 mb-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-pie-chart-line me-2"></i>Cost Distribution by Department
                    </h5>
                </div>
                <div class="card-body">
                    <canvas id="departmentCostChart" height="300"></canvas>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-md-12 mb-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-bar-chart-line me-2"></i>Efficiency by Department
                    </h5>
                </div>
                <div class="card-body">
                    <canvas id="departmentEfficiencyChart" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- Organizational Insights -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i class="ri-lightbulb-line me-2"></i>Organizational Insights & Recommendations
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6 col-md-12 mb-3">
                            <h6 class="text-primary">Key Insights</h6>
                            <ul class="list-unstyled">
                                <li class="mb-2">
                                    <i class="ri-check-line text-success me-2"></i>
                                    <strong>Total Investment:</strong> KES <?= number_format($orgEmployeeMetrics['organizational_insights']['total_investment'], 0) ?>
                                </li>
                                <li class="mb-2">
                                    <i class="ri-check-line text-success me-2"></i>
                                    <strong>Total Return:</strong> KES <?= number_format($orgEmployeeMetrics['organizational_insights']['total_return'], 0) ?>
                                </li>
                                <li class="mb-2">
                                    <i class="ri-check-line text-success me-2"></i>
                                    <strong>Most Efficient Department:</strong> <?= htmlspecialchars($orgEmployeeMetrics['organizational_insights']['most_efficient_department']) ?>
                                </li>
                                <li class="mb-2">
                                    <i class="ri-check-line text-success me-2"></i>
                                    <strong>Most Efficient Role:</strong> <?= htmlspecialchars($orgEmployeeMetrics['organizational_insights']['most_efficient_role']) ?>
                                </li>
                            </ul>
                        </div>
                        <div class="col-xl-6 col-md-12 mb-3">
                            <h6 class="text-warning">Recommendations</h6>
                            <ul class="list-unstyled">
                                <li class="mb-2">
                                    <i class="ri-arrow-right-line text-info me-2"></i>
                                    Focus on replicating high performer strategies across the organization
                                </li>
                                <li class="mb-2">
                                    <i class="ri-arrow-right-line text-info me-2"></i>
                                    Provide additional training for low-performing employees
                                </li>
                                <li class="mb-2">
                                    <i class="ri-arrow-right-line text-info me-2"></i>
                                    Consider role optimization based on efficiency scores
                                </li>
                                <li class="mb-2">
                                    <i class="ri-arrow-right-line text-info me-2"></i>
                                    Implement performance-based incentives for high performers
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Department Cost Chart
    const departmentCostCtx = document.getElementById('departmentCostChart');
    if (departmentCostCtx) {
        const departmentData = <?= json_encode($orgEmployeeMetrics['department_analysis']) ?>;
        const deptLabels = Object.keys(departmentData);
        const costData = deptLabels.map(label => departmentData[label]['total_cost']);
        
        new Chart(departmentCostCtx, {
            type: 'doughnut',
            data: {
                labels: deptLabels,
                datasets: [{
                    data: costData,
                    backgroundColor: [
                        '#28a745', '#17a2b8', '#ffc107', '#dc3545', '#6f42c1', '#6c757d'
                    ],
                    borderWidth: 2,
                    borderColor: '#fff'
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'bottom',
                        labels: {
                            padding: 20,
                            usePointStyle: true
                        }
                    },
                    tooltip: {
                        callbacks: {
                            label: function(context) {
                                const value = context.parsed;
                                const total = context.dataset.data.reduce((a, b) => a + b, 0);
                                const percentage = total > 0 ? ((value / total) * 100).toFixed(1) : '0.0';
                                return context.label + ': KES ' + value.toLocaleString() + ' (' + percentage + '%)';
                            }
                        }
                    }
                }
            }
        });
    }

    // Department Efficiency Chart
    const departmentEfficiencyCtx = document.getElementById('departmentEfficiencyChart');
    if (departmentEfficiencyCtx) {
        const departmentData = <?= json_encode($orgEmployeeMetrics['department_analysis']) ?>;
        const deptLabels = Object.keys(departmentData);
        const efficiencyData = deptLabels.map(label => departmentData[label]['efficiency_score']);
        
        new Chart(departmentEfficiencyCtx, {
            type: 'bar',
            data: {
                labels: deptLabels,
                datasets: [{
                    label: 'Efficiency Score',
                    data: efficiencyData,
                    backgroundColor: efficiencyData.map(score => {
                        if (score >= 200) return '#28a745';
                        if (score >= 100) return '#ffc107';
                        return '#dc3545';
                    }),
                    borderColor: efficiencyData.map(score => {
                        if (score >= 200) return '#28a745';
                        if (score >= 100) return '#ffc107';
                        return '#dc3545';
                    }),
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true,
                        ticks: {
                            callback: function(value) {
                                return value + '%';
                            }
                        }
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    },
                    tooltip: {
                        callbacks: {
                            label: function(context) {
                                return 'Efficiency Score: ' + context.parsed.y + '%';
                            }
                        }
                    }
                }
            }
        });
    }
});
</script>
